const $ = (query, root = document) => root.querySelector(query);
const $$ = (query, root = document) => [...root.querySelectorAll(query)];

$('#year').textContent = new Date().getFullYear();

const header = $('.site-header');
const menu = $('#main-nav');
const menuButton = $('.menu-button');

menuButton.addEventListener('click', () => {
  const open = menuButton.getAttribute('aria-expanded') === 'true';
  menuButton.setAttribute('aria-expanded', String(!open));
  menu.classList.toggle('open', !open);
});

$$('a', menu).forEach(link => link.addEventListener('click', () => {
  menu.classList.remove('open');
  menuButton.setAttribute('aria-expanded', 'false');
}));

addEventListener('scroll', () => {
  header.classList.toggle('scrolled', scrollY > 24);
  if (!matchMedia('(prefers-reduced-motion: reduce)').matches && scrollY < innerHeight) {
    $('.hero-background img').style.transform = `scale(1.015) translateY(${scrollY * .045}px)`;
  }
}, { passive: true });

const revealObserver = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add('visible');
      revealObserver.unobserve(entry.target);
    }
  });
}, { threshold: .07, rootMargin: '0px 0px -30px' });
// Observation happens after the sections below are rendered, so that
// generated .reveal elements are picked up too.

const navLinks = $$('a', menu);
const sections = ['photography', 'music', 'software', 'notes'].map(id => document.getElementById(id));
const sectionObserver = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (!entry.isIntersecting) return;
    navLinks.forEach(link => link.classList.toggle('active', link.getAttribute('href') === `#${entry.target.id}`));
  });
}, { rootMargin: '-35% 0px -55%' });
sections.forEach(section => sectionObserver.observe(section));

/* ---------------------------------------------------------------
   Content rendered from data.js (generated by build.mjs).
   --------------------------------------------------------------- */

const DATA = window.SITE_DATA || { photos: [], tracks: [], notes: [] };

const el = (tag, className, text) => {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text != null) node.textContent = text;
  return node;
};

const empty = message => {
  const node = el('p', 'empty-note', message);
  return node;
};

/* ---------- photography ---------- */

const PER_PAGE = 9;

const photoTile = (photo, index) => {
  const button = el('button', 'photo');
  button.type = 'button';
  // Tiles load the small copy; the lightbox gets the large one. Both fall
  // back to the original if the build couldn't produce a derivative.
  button.dataset.image = photo.full || photo.src;
  button.dataset.caption = photo.title;
  // Shape drives how many grid cells the tile claims.
  button.dataset.shape = photo.shape || 'square';

  const image = el('img');
  image.src = photo.grid || photo.src;
  image.alt = photo.subtitle ? `${photo.title} — ${photo.subtitle}` : photo.title;
  // Known up front from the build, so the browser reserves the right box
  // before the file arrives and nothing jumps as images load.
  if (photo.width) { image.width = photo.width; image.height = photo.height; }
  // Only the first page loads eagerly; later pages wait until scrolled to.
  image.setAttribute('loading', index < PER_PAGE ? 'eager' : 'lazy');
  image.setAttribute('decoding', 'async');

  const label = el('span');
  label.append(el('b', null, photo.title));
  if (photo.subtitle) label.append(el('small', null, photo.subtitle));

  button.append(image, label);
  return button;
};

const photoGrid = $('#photo-grid');
if (photoGrid) {
  if (!DATA.photos.length) {
    photoGrid.append(empty('Drop image files into the images folder and run the build.'));
  } else {
    const pageCount = Math.ceil(DATA.photos.length / PER_PAGE);

    // reveal lives on the track, not the pages — a page scrolled out of
    // view horizontally never intersects, and would stay invisible.
    const track = el('div', 'gallery-track reveal');
    track.id = 'gallery-track';
    track.tabIndex = 0;
    track.setAttribute('role', 'region');
    track.setAttribute('aria-label', `Photographs, ${pageCount} page${pageCount > 1 ? 's' : ''}`);

    for (let page = 0; page < pageCount; page++) {
      const panel = el('div', 'gallery-page');
      panel.setAttribute('aria-label', `Page ${page + 1} of ${pageCount}`);
      DATA.photos
        .slice(page * PER_PAGE, (page + 1) * PER_PAGE)
        .forEach((photo, offset) => panel.append(photoTile(photo, page * PER_PAGE + offset)));
      track.append(panel);
    }
    photoGrid.append(track);

    if (pageCount > 1) buildGalleryNav(photoGrid, track, pageCount);
  }
}

function buildGalleryNav(root, track, pageCount) {
  const nav = el('div', 'gallery-nav');

  const arrow = (direction, label, glyph) => {
    const button = el('button', `gallery-arrow gallery-${direction}`);
    button.type = 'button';
    button.setAttribute('aria-label', label);
    button.append(el('span', null, glyph));
    button.addEventListener('click', () => goToPage(currentPage() + (direction === 'next' ? 1 : -1)));
    return button;
  };

  const dots = el('div', 'gallery-dots');
  for (let page = 0; page < pageCount; page++) {
    const dot = el('button', 'gallery-dot');
    dot.type = 'button';
    dot.setAttribute('aria-label', `Go to page ${page + 1}`);
    dot.addEventListener('click', () => goToPage(page));
    dots.append(dot);
  }

  const previous = arrow('prev', 'Previous page', '←');
  const next = arrow('next', 'Next page', '→');
  nav.append(previous, dots, next);
  root.append(nav);

  // Guarded: width is 0 before first layout, and 0/0 would give NaN.
  const pageWidth = () => track.firstElementChild.getBoundingClientRect().width || 0;
  const currentPage = () => {
    const width = pageWidth();
    return width ? Math.round(track.scrollLeft / width) : 0;
  };

  function goToPage(page) {
    const target = Math.max(0, Math.min(pageCount - 1, page));
    track.scrollTo({ left: target * pageWidth(), behavior: 'smooth' });
  }

  const syncNav = () => {
    const page = currentPage();
    [...dots.children].forEach((dot, index) => {
      dot.classList.toggle('active', index === page);
      dot.setAttribute('aria-current', index === page ? 'true' : 'false');
    });
    previous.disabled = page === 0;
    next.disabled = page === pageCount - 1;
  };

  let frame = null;
  track.addEventListener('scroll', () => {
    if (frame) return;
    frame = requestAnimationFrame(() => { frame = null; syncNav(); });
  }, { passive: true });

  track.addEventListener('keydown', event => {
    if (event.key === 'ArrowRight') { event.preventDefault(); goToPage(currentPage() + 1); }
    if (event.key === 'ArrowLeft') { event.preventDefault(); goToPage(currentPage() - 1); }
  });

  addEventListener('resize', syncNav);
  syncNav();
}

/* ---------- music ---------- */

const trackList = $('#track-list');
const player = new Audio();
let currentTrack = null;

const clock = seconds => Number.isFinite(seconds)
  ? `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`
  : '—:—';

if (trackList) {
  if (!DATA.tracks.length) {
    trackList.append(empty('Drop MP3s into the music folder and run the build.'));
  } else {
    DATA.tracks.forEach(track => {
      const row = el('div', 'track');
      row.dataset.src = track.src;

      const button = el('button');
      button.type = 'button';
      button.setAttribute('aria-label', `Play ${track.title}`);
      button.append(el('span', 'glyph', '▶'));

      const label = el('span');
      label.append(el('b', null, track.title));
      if (track.subtitle) label.append(el('small', null, track.subtitle));

      const time = el('time', null, '—:—');

      // Ask the browser for just the header so we can show a duration
      // without downloading the whole file.
      const probe = new Audio();
      probe.preload = 'metadata';
      probe.addEventListener('loadedmetadata', () => { time.textContent = clock(probe.duration); });
      probe.src = track.src;

      button.addEventListener('click', () => toggleTrack(row));
      row.append(button, label, time);
      trackList.append(row);
    });
  }
}

function toggleTrack(row) {
  if (currentTrack === row) {
    player.paused ? player.play() : player.pause();
    return;
  }
  if (currentTrack) currentTrack.classList.remove('playing');
  currentTrack = row;
  row.classList.add('playing');
  player.src = row.dataset.src;
  player.play().catch(() => row.classList.remove('playing'));
}

const syncPlayer = () => {
  const playing = currentTrack && !player.paused && !player.ended;
  $$('.track').forEach(row => {
    const active = row === currentTrack && playing;
    row.classList.toggle('playing', Boolean(active));
    const glyph = $('.glyph', row);
    if (glyph) glyph.textContent = active ? '❚❚' : '▶';
  });
  $$('.waveform').forEach(wave => wave.classList.toggle('active', Boolean(playing)));
};

['play', 'pause', 'ended'].forEach(event => player.addEventListener(event, syncPlayer));
player.addEventListener('ended', () => { currentTrack = null; syncPlayer(); });

/* ---------- notes ---------- */

const noteList = $('#note-list');
if (noteList) {
  if (!DATA.notes.length) {
    noteList.append(empty('Write a markdown file into the notes folder and run the build.'));
  } else {
    DATA.notes.forEach((note, index) => {
      const article = el('article', 'note reveal');

      const time = el('time', null, note.date ? formatDate(note.date) : 'Draft');
      if (note.date) time.dateTime = note.date;

      const middle = el('div');
      middle.append(el('small', null, note.kicker));
      middle.append(el('h3', null, note.title));
      if (note.summary) middle.append(el('p', null, note.summary));

      const toggle = el('button', 'note-toggle');
      toggle.type = 'button';
      toggle.innerHTML = '<span aria-hidden="true">↗</span>';
      toggle.setAttribute('aria-expanded', 'false');
      toggle.setAttribute('aria-controls', `note-body-${index}`);
      toggle.append(el('span', 'sr-only', `Read ${note.title}`));

      const body = el('div', 'note-body');
      body.id = `note-body-${index}`;
      const inner = el('div', 'note-body-inner');
      inner.innerHTML = note.html;
      body.append(inner);

      toggle.addEventListener('click', () => {
        const open = article.classList.toggle('open');
        toggle.setAttribute('aria-expanded', String(open));
      });

      article.append(time, middle, toggle, body);
      noteList.append(article);
    });
  }
}

function formatDate(iso) {
  const [year, month, day] = iso.split('-');
  return `${day}.${month}.${year.slice(2)}`;
}

// Everything above is now in the DOM — start watching for reveals.
$$('.reveal').forEach(item => revealObserver.observe(item));

const stack = $('#polaroid-stack');
if (stack) {
  const cards = $$('.card', stack);
  let order = [...cards];

  const restack = () => order.forEach((card, index) => {
    card.classList.remove('slot-1', 'slot-2', 'slot-3');
    card.classList.add(`slot-${index + 1}`);
    $('.card-hit', card).setAttribute('aria-disabled', String(index === 0));
  });

  cards.forEach(card => $('.card-hit', card).addEventListener('click', () => {
    if (order[0] === card) return;
    order = [card, ...order.filter(other => other !== card)];
    restack();
  }));

  restack();
}

const lightbox = $('#lightbox');
$$('.photo').forEach(button => button.addEventListener('click', () => {
  const image = $('img', lightbox);
  image.src = button.dataset.image;
  image.alt = $('img', button).alt;
  $('p', lightbox).textContent = button.dataset.caption;
  lightbox.showModal();
}));

$('button', lightbox).addEventListener('click', () => lightbox.close());
lightbox.addEventListener('click', event => {
  if (event.target === lightbox) lightbox.close();
});
