/* Generated by update-lists.mjs — do not edit by hand. */
window.TRACKS = [
  {
    "sort": 1,
    "date": null,
    "title": "First Light",
    "subtitle": "Instrumental Rock",
    "src": "music/01 - First Light - Instrumental Rock.mp3"
  }
];
