/* Generated by make-web.mjs — do not edit by hand. */
window.PHOTOS = [
  {
    "title": "My Mother",
    "subtitle": "Airfield Estate",
    "width": 1023,
    "height": 1537,
    "shape": "portrait",
    "grid": "images/_web/01 - My Mother - Airfield Estate-grid.webp",
    "full": "images/_web/01 - My Mother - Airfield Estate-full.webp"
  },
  {
    "title": "The Véro Dodat Gallery",
    "subtitle": "Paris",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/_web/02 - The Véro Dodat Gallery - Paris -grid.webp",
    "full": "images/_web/02 - The Véro Dodat Gallery - Paris -full.webp"
  },
  {
    "title": "The Moon",
    "subtitle": "Over Open Water",
    "width": 4160,
    "height": 6240,
    "shape": "portrait",
    "grid": "images/_web/03 - The Moon - Over Open Water-grid.webp",
    "full": "images/_web/03 - The Moon - Over Open Water-full.webp"
  },
  {
    "title": "Butterfly",
    "subtitle": "Malahide Castle",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/_web/04 - Butterfly - Malahide Castle-grid.webp",
    "full": "images/_web/04 - Butterfly - Malahide Castle-full.webp"
  },
  {
    "title": "East Pier At Sunset",
    "subtitle": "Dun Laoghaire",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/05 - East Pier At Sunset - Dun Laoghaire-grid.webp",
    "full": "images/_web/05 - East Pier At Sunset - Dun Laoghaire-full.webp"
  },
  {
    "title": "Best Boys",
    "subtitle": "Blackrock",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/06 - Best Boys - Blackrock-grid.webp",
    "full": "images/_web/06 - Best Boys - Blackrock-full.webp"
  },
  {
    "title": "Swans",
    "subtitle": "Stillness, briefly",
    "width": 1400,
    "height": 933,
    "shape": "landscape",
    "grid": "images/_web/07 - Swans - Stillness, briefly-grid.webp",
    "full": "images/_web/07 - Swans - Stillness, briefly-full.webp"
  },
  {
    "title": "The Louvre",
    "subtitle": "Paris",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/_web/08 - The Louvre - Paris-grid.webp",
    "full": "images/_web/08 - The Louvre - Paris-full.webp"
  },
  {
    "title": "Full Steam Ahead",
    "subtitle": "Dun Laoghaire West Pier",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/_web/10 - Full Steam Ahead - Dun Laoghaire West Pier-grid.webp",
    "full": "images/_web/10 - Full Steam Ahead - Dun Laoghaire West Pier-full.webp"
  },
  {
    "title": "Dinner At Night",
    "subtitle": "Florence Italy",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/_web/11 - Dinner At Night - Florence Italy-grid.webp",
    "full": "images/_web/11 - Dinner At Night - Florence Italy-full.webp"
  },
  {
    "title": "The Obelisk",
    "subtitle": "Killiney Hill",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/12 - The Obelisk - Killiney Hill -grid.webp",
    "full": "images/_web/12 - The Obelisk - Killiney Hill -full.webp"
  },
  {
    "title": "Mama & Son",
    "subtitle": "Dublin Zoo",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/13 - Mama & Son - Dublin Zoo-grid.webp",
    "full": "images/_web/13 - Mama & Son - Dublin Zoo-full.webp"
  },
  {
    "title": "Mama & Son",
    "subtitle": "Dublin Zoo",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/14 - Mama & Son - Dublin Zoo-grid.webp",
    "full": "images/_web/14 - Mama & Son - Dublin Zoo-full.webp"
  },
  {
    "title": "Big Stretch",
    "subtitle": "Dublin Zoo",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/15 - Big Stretch - Dublin Zoo-grid.webp",
    "full": "images/_web/15 - Big Stretch - Dublin Zoo-full.webp"
  },
  {
    "title": "Sleepy Head",
    "subtitle": "Dublin Zoo",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/_web/16 - Sleepy Head - Dublin Zoo-grid.webp",
    "full": "images/_web/16 - Sleepy Head - Dublin Zoo-full.webp"
  },
  {
    "title": "Hanging The Moon",
    "subtitle": "Dalkey",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/_web/17 - Hanging The Moon - Dalkey-grid.webp",
    "full": "images/_web/17 - Hanging The Moon - Dalkey-full.webp"
  },
  {
    "title": "Autumn Colours",
    "subtitle": "Cabinteely",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/18 - Autumn Colours - Cabinteely-grid.webp",
    "full": "images/_web/18 - Autumn Colours - Cabinteely-full.webp"
  },
  {
    "title": "Straton Speciale",
    "subtitle": "Straton Watches",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/19 - Straton Speciale - Straton Watches-grid.webp",
    "full": "images/_web/19 - Straton Speciale - Straton Watches-full.webp"
  },
  {
    "title": "Reflections",
    "subtitle": "Paris",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/_web/20 - Reflections - Paris-grid.webp",
    "full": "images/_web/20 - Reflections - Paris-full.webp"
  },
  {
    "title": "The Jungle’s Smallest Lookout.",
    "subtitle": "Dublin Zoo",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/21 - The Jungle’s Smallest Lookout. - Dublin Zoo -grid.webp",
    "full": "images/_web/21 - The Jungle’s Smallest Lookout. - Dublin Zoo -full.webp"
  },
  {
    "title": "Oh Ship!",
    "subtitle": "South Wall",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/22 - Oh Ship! - South Wall-grid.webp",
    "full": "images/_web/22 - Oh Ship! - South Wall-full.webp"
  },
  {
    "title": "Should I Sneak A Treat",
    "subtitle": "Newbridge Farm",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/_web/23 - Should I Sneak A Treat - Newbridge Farm-grid.webp",
    "full": "images/_web/23 - Should I Sneak A Treat - Newbridge Farm-full.webp"
  },
  {
    "title": "I Should Sneak A Treat",
    "subtitle": "Newbridge Farm",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/_web/24 - I Should Sneak A Treat - Newbridge Farm-grid.webp",
    "full": "images/_web/24 - I Should Sneak A Treat - Newbridge Farm-full.webp"
  },
  {
    "title": "Just A Kid With Big City Dreams.",
    "subtitle": "Mullins Hill",
    "width": 1537,
    "height": 1023,
    "shape": "landscape",
    "grid": "images/_web/25 - Just A Kid With Big City Dreams. - Mullins Hill-grid.webp",
    "full": "images/_web/25 - Just A Kid With Big City Dreams. - Mullins Hill-full.webp"
  },
  {
    "title": "No Leopard Like A Snow Leopard",
    "subtitle": "Dublin Zoo",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/_web/26 - No Leopard Like A Snow Leopard - Dublin Zoo-grid.webp",
    "full": "images/_web/26 - No Leopard Like A Snow Leopard - Dublin Zoo-full.webp"
  },
  {
    "title": "Big Cheese",
    "subtitle": "Moon",
    "width": 2576,
    "height": 3864,
    "shape": "portrait",
    "grid": "images/_web/27 - Big Cheese - Moon-grid.webp",
    "full": "images/_web/27 - Big Cheese - Moon-full.webp"
  },
  {
    "title": "Seal Stepped On Lego",
    "subtitle": "Dun Laoghaire",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/28 - Seal Stepped On Lego - Dun Laoghaire-grid.webp",
    "full": "images/_web/28 - Seal Stepped On Lego - Dun Laoghaire-full.webp"
  },
  {
    "title": "Me",
    "subtitle": "Dun Laoghaire",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/29 - Me - Dun Laoghaire-grid.webp",
    "full": "images/_web/29 - Me - Dun Laoghaire-full.webp"
  },
  {
    "title": "A Time For Reflection",
    "subtitle": "Glendalough",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/30 - A Time For Reflection - Glendalough-grid.webp",
    "full": "images/_web/30 - A Time For Reflection - Glendalough-full.webp"
  },
  {
    "title": "Greatest Car Ever Made",
    "subtitle": "Paris",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/_web/31 - Greatest Car Ever Made - Paris-grid.webp",
    "full": "images/_web/31 - Greatest Car Ever Made - Paris-full.webp"
  },
  {
    "title": "Heart Shaped Butt",
    "subtitle": "Glendalough",
    "width": 3000,
    "height": 3000,
    "shape": "square",
    "grid": "images/_web/32 - Heart Shaped Butt - Glendalough-grid.webp",
    "full": "images/_web/32 - Heart Shaped Butt - Glendalough-full.webp"
  },
  {
    "title": "Butterfly",
    "subtitle": "Amsterdam",
    "width": 1040,
    "height": 1560,
    "shape": "portrait",
    "grid": "images/_web/33 - Butterfly - Amsterdam-grid.webp",
    "full": "images/_web/33 - Butterfly - Amsterdam-full.webp"
  },
  {
    "title": "Wildlights",
    "subtitle": "Dublin Zoo",
    "width": 2576,
    "height": 3864,
    "shape": "portrait",
    "grid": "images/_web/34 - Wildlights - Dublin Zoo-grid.webp",
    "full": "images/_web/34 - Wildlights - Dublin Zoo-full.webp"
  },
  {
    "title": "Wildlights",
    "subtitle": "Dublin Zoo",
    "width": 2576,
    "height": 3864,
    "shape": "portrait",
    "grid": "images/_web/35 - Wildlights - Dublin Zoo-grid.webp",
    "full": "images/_web/35 - Wildlights - Dublin Zoo-full.webp"
  },
  {
    "title": "Person",
    "subtitle": "Peoples Park",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/36 - Person - Peoples Park-grid.webp",
    "full": "images/_web/36 - Person - Peoples Park-full.webp"
  },
  {
    "title": "Resevoir In The Mist",
    "subtitle": "Roundwood",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/37 - Resevoir In The Mist - Roundwood-grid.webp",
    "full": "images/_web/37 - Resevoir In The Mist - Roundwood-full.webp"
  },
  {
    "title": "Dragonflying",
    "subtitle": "Cabinteely Park",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/_web/38 - Dragonflying - Cabinteely Park-grid.webp",
    "full": "images/_web/38 - Dragonflying - Cabinteely Park-full.webp"
  },
  {
    "title": "Dragonresting- Mount Usher",
    "subtitle": null,
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/_web/39 - Dragonresting- Mount Usher-grid.webp",
    "full": "images/_web/39 - Dragonresting- Mount Usher-full.webp"
  }
];
