/* Generated by make-web.mjs — do not edit by hand. */
window.PHOTOS = [
  {
    "title": "My Mother",
    "subtitle": "Airfield Estate",
    "width": 1023,
    "height": 1537,
    "shape": "portrait",
    "grid": "images/01 - My Mother - Airfield Estate-grid.webp",
    "full": "images/01 - My Mother - Airfield Estate-full.webp"
  },
  {
    "title": "The Véro Dodat Gallery",
    "subtitle": "Paris",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/02 - The Véro Dodat Gallery - Paris-grid.webp",
    "full": "images/02 - The Véro Dodat Gallery - Paris-full.webp"
  },
  {
    "title": "The Moon",
    "subtitle": "Dalkey",
    "width": 4160,
    "height": 6240,
    "shape": "portrait",
    "grid": "images/03 - The Moon - Dalkey-grid.webp",
    "full": "images/03 - The Moon - Dalkey-full.webp"
  },
  {
    "title": "Butterfly",
    "subtitle": "Malahide Castle",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/04 - Butterfly - Malahide Castle-grid.webp",
    "full": "images/04 - Butterfly - Malahide Castle-full.webp"
  },
  {
    "title": "East Pier At Sunset",
    "subtitle": "Dun Laoghaire",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/05 - East Pier At Sunset - Dun Laoghaire-grid.webp",
    "full": "images/05 - East Pier At Sunset - Dun Laoghaire-full.webp"
  },
  {
    "title": "Best Boys",
    "subtitle": "Blackrock",
    "width": 2528,
    "height": 1696,
    "shape": "landscape",
    "grid": "images/06 - Best Boys - Blackrock-grid.webp",
    "full": "images/06 - Best Boys - Blackrock-full.webp"
  },
  {
    "title": "Swans",
    "subtitle": "Stillness, briefly",
    "width": 1400,
    "height": 933,
    "shape": "landscape",
    "grid": "images/07 - Swans - Stillness, briefly-grid.webp",
    "full": "images/07 - Swans - Stillness, briefly-full.webp"
  },
  {
    "title": "The Louvre",
    "subtitle": "Paris",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/08 - The Louvre - Paris-grid.webp",
    "full": "images/08 - The Louvre - Paris-full.webp"
  },
  {
    "title": "Full Steam Ahead",
    "subtitle": "Dun Laoghaire West Pier",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/10 - Full Steam Ahead - Dun Laoghaire West Pier-grid.webp",
    "full": "images/10 - Full Steam Ahead - Dun Laoghaire West Pier-full.webp"
  },
  {
    "title": "Dinner At Night",
    "subtitle": "Florence Italy",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/11 - Dinner At Night - Florence Italy-grid.webp",
    "full": "images/11 - Dinner At Night - Florence Italy-full.webp"
  },
  {
    "title": "The Obelisk",
    "subtitle": "Killiney Hill",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/12 - The Obelisk - Killiney Hill-grid.webp",
    "full": "images/12 - The Obelisk - Killiney Hill-full.webp"
  },
  {
    "title": "Mama & Son",
    "subtitle": "Dublin Zoo",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/13 - Mama and Son - Dublin Zoo-grid.webp",
    "full": "images/13 - Mama and Son - Dublin Zoo-full.webp"
  },
  {
    "title": "Mama & Son",
    "subtitle": "Dublin Zoo",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/14 - Mama and Son - Dublin Zoo-grid.webp",
    "full": "images/14 - Mama and Son - Dublin Zoo-full.webp"
  },
  {
    "title": "Big Stretch",
    "subtitle": "Dublin Zoo",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/15 - Big Stretch - Dublin Zoo-grid.webp",
    "full": "images/15 - Big Stretch - Dublin Zoo-full.webp"
  },
  {
    "title": "Sleepy Head",
    "subtitle": "Dublin Zoo",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/16 - Sleepy Head - Dublin Zoo-grid.webp",
    "full": "images/16 - Sleepy Head - Dublin Zoo-full.webp"
  },
  {
    "title": "Hanging The Moon",
    "subtitle": "Dalkey",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/17 - Hanging The Moon - Dalkey-grid.webp",
    "full": "images/17 - Hanging The Moon - Dalkey-full.webp"
  },
  {
    "title": "Autumn Colours",
    "subtitle": "Cabinteely",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/18 - Autumn Colours - Cabinteely-grid.webp",
    "full": "images/18 - Autumn Colours - Cabinteely-full.webp"
  },
  {
    "title": "Straton Speciale",
    "subtitle": "Straton Watches",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/19 - Straton Speciale - Straton Watches-grid.webp",
    "full": "images/19 - Straton Speciale - Straton Watches-full.webp"
  },
  {
    "title": "Reflections",
    "subtitle": "Paris",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/20 - Reflections - Paris-grid.webp",
    "full": "images/20 - Reflections - Paris-full.webp"
  },
  {
    "title": "The Jungle’s Smallest Lookout.",
    "subtitle": "Dublin Zoo",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/21 - The Jungle's Smallest Lookout. - Dublin Zoo-grid.webp",
    "full": "images/21 - The Jungle's Smallest Lookout. - Dublin Zoo-full.webp"
  },
  {
    "title": "Oh Ship!",
    "subtitle": "South Wall",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/22 - Oh Ship! - South Wall-grid.webp",
    "full": "images/22 - Oh Ship! - South Wall-full.webp"
  },
  {
    "title": "Should I Sneak A Treat",
    "subtitle": "Newbridge Farm",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/23 - Should I Sneak A Treat - Newbridge Farm-grid.webp",
    "full": "images/23 - Should I Sneak A Treat - Newbridge Farm-full.webp"
  },
  {
    "title": "I Should Sneak A Treat",
    "subtitle": "Newbridge Farm",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/24 - I Should Sneak A Treat - Newbridge Farm-grid.webp",
    "full": "images/24 - I Should Sneak A Treat - Newbridge Farm-full.webp"
  },
  {
    "title": "Just A Kid With Big City Dreams.",
    "subtitle": "Mullins Hill",
    "width": 1537,
    "height": 1023,
    "shape": "landscape",
    "grid": "images/25 - Just A Kid With Big City Dreams. - Mullins Hill-grid.webp",
    "full": "images/25 - Just A Kid With Big City Dreams. - Mullins Hill-full.webp"
  },
  {
    "title": "No Leopard Like A Snow Leopard",
    "subtitle": "Dublin Zoo",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/26 - No Leopard Like A Snow Leopard - Dublin Zoo-grid.webp",
    "full": "images/26 - No Leopard Like A Snow Leopard - Dublin Zoo-full.webp"
  },
  {
    "title": "Big Cheese",
    "subtitle": "Moon",
    "width": 2576,
    "height": 3864,
    "shape": "portrait",
    "grid": "images/27 - Big Cheese - Moon-grid.webp",
    "full": "images/27 - Big Cheese - Moon-full.webp"
  },
  {
    "title": "Seal Stepped On Lego",
    "subtitle": "Dun Laoghaire",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/28 - Seal Stepped On Lego - Dun Laoghaire-grid.webp",
    "full": "images/28 - Seal Stepped On Lego - Dun Laoghaire-full.webp"
  },
  {
    "title": "Me",
    "subtitle": "Dun Laoghaire",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/29 - Me - Dun Laoghaire-grid.webp",
    "full": "images/29 - Me - Dun Laoghaire-full.webp"
  },
  {
    "title": "A Time For Reflection",
    "subtitle": "Glendalough",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/30 - A Time For Reflection - Glendalough-grid.webp",
    "full": "images/30 - A Time For Reflection - Glendalough-full.webp"
  },
  {
    "title": "Greatest Car Ever Made",
    "subtitle": "Paris",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/31 - Greatest Car Ever Made - Paris-grid.webp",
    "full": "images/31 - Greatest Car Ever Made - Paris-full.webp"
  },
  {
    "title": "Heart Shaped Butt",
    "subtitle": "Glendalough",
    "width": 3000,
    "height": 3000,
    "shape": "square",
    "grid": "images/32 - Heart Shaped Butt - Glendalough-grid.webp",
    "full": "images/32 - Heart Shaped Butt - Glendalough-full.webp"
  },
  {
    "title": "Butterfly",
    "subtitle": "Amsterdam",
    "width": 1040,
    "height": 1560,
    "shape": "portrait",
    "grid": "images/33 - Butterfly - Amsterdam-grid.webp",
    "full": "images/33 - Butterfly - Amsterdam-full.webp"
  },
  {
    "title": "Wildlights",
    "subtitle": "Dublin Zoo",
    "width": 2576,
    "height": 3864,
    "shape": "portrait",
    "grid": "images/34 - Wildlights - Dublin Zoo-grid.webp",
    "full": "images/34 - Wildlights - Dublin Zoo-full.webp"
  },
  {
    "title": "Wildlights",
    "subtitle": "Dublin Zoo",
    "width": 2576,
    "height": 3864,
    "shape": "portrait",
    "grid": "images/35 - Wildlights - Dublin Zoo-grid.webp",
    "full": "images/35 - Wildlights - Dublin Zoo-full.webp"
  },
  {
    "title": "Music In The Park",
    "subtitle": "Peoples Park",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/36 - Music In The Park - Peoples Park-grid.webp",
    "full": "images/36 - Music In The Park - Peoples Park-full.webp"
  },
  {
    "title": "Moonlit Solitude",
    "subtitle": "Dun Laoghaire",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/37 - Moonlit Solitude - Dun Laoghaire-grid.webp",
    "full": "images/37 - Moonlit Solitude - Dun Laoghaire-full.webp"
  },
  {
    "title": "Dragonflying",
    "subtitle": "Cabinteely Park",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/38 - Dragonflying - Cabinteely Park-grid.webp",
    "full": "images/38 - Dragonflying - Cabinteely Park-full.webp"
  },
  {
    "title": "Dragonresting",
    "subtitle": "Mount Usher",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/39 - Dragonresting - Mount Usher-grid.webp",
    "full": "images/39 - Dragonresting - Mount Usher-full.webp"
  },
  {
    "title": "When your Fringe Is Flawless But Your Table Manners Aren’t.",
    "subtitle": "Kilruddery Estate",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/40 - When your Fringe Is Flawless But Your Table Manners Aren't. - Kilruddery Estate-grid.webp",
    "full": "images/40 - When your Fringe Is Flawless But Your Table Manners Aren't. - Kilruddery Estate-full.webp"
  },
  {
    "title": "Atlantic Fury",
    "subtitle": "The 40 Foot",
    "width": 1536,
    "height": 1024,
    "shape": "landscape",
    "grid": "images/41 - Atlantic Fury - The 40 Foot-grid.webp",
    "full": "images/41 - Atlantic Fury - The 40 Foot-full.webp"
  },
  {
    "title": "In Full Bloom",
    "subtitle": "Cabinteely Park",
    "width": 3091,
    "height": 2061,
    "shape": "landscape",
    "grid": "images/42 - In Full Bloom - Cabinteely Park-grid.webp",
    "full": "images/42 - In Full Bloom - Cabinteely Park-full.webp"
  },
  {
    "title": "Resevoir In The Mist",
    "subtitle": "Roundwood",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/43 - Resevoir In The Mist - Roundwood-grid.webp",
    "full": "images/43 - Resevoir In The Mist - Roundwood-full.webp"
  },
  {
    "title": "Grace in Motion",
    "subtitle": "Merrion Park",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/44 - Grace in Motion - Merrion Park-grid.webp",
    "full": "images/44 - Grace in Motion - Merrion Park-full.webp"
  },
  {
    "title": "Emerald Watch",
    "subtitle": "Dublin Zoo",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/45 - Emerald Watch - Dublin Zoo-grid.webp",
    "full": "images/45 - Emerald Watch - Dublin Zoo-full.webp"
  },
  {
    "title": "Poolbeg Your Pardon",
    "subtitle": "Dun Laoghaire Pier",
    "width": 2576,
    "height": 3864,
    "shape": "portrait",
    "grid": "images/46 - Poolbeg Your Pardon - Dun Laoghaire Pier-grid.webp",
    "full": "images/46 - Poolbeg Your Pardon - Dun Laoghaire Pier-full.webp"
  },
  {
    "title": "Autumn Dash",
    "subtitle": "Botanical Gardens",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/47 - Autumn Dash - Botanical Gardens-grid.webp",
    "full": "images/47 - Autumn Dash - Botanical Gardens-full.webp"
  },
  {
    "title": "Golden Moonrise",
    "subtitle": "Dun Laoghaire",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/48 - Golden Moonrise - Dun Laoghaire-grid.webp",
    "full": "images/48 - Golden Moonrise - Dun Laoghaire-full.webp"
  },
  {
    "title": "Framed by Moonlight",
    "subtitle": "My Back Garden",
    "width": 6240,
    "height": 4160,
    "shape": "landscape",
    "grid": "images/49 - Framed by Moonlight - My Back Garden-grid.webp",
    "full": "images/49 - Framed by Moonlight - My Back Garden-full.webp"
  },
  {
    "title": "Seapoint at Dusk",
    "subtitle": "Seapoint",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/50 - Seapoint at Dusk - Seapoint-grid.webp",
    "full": "images/50 - Seapoint at Dusk - Seapoint-full.webp"
  },
  {
    "title": "Coming Into Land",
    "subtitle": "Dun Laoghaire",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/51 - Coming Into Land - Dun Laoghaire-grid.webp",
    "full": "images/51 - Coming Into Land - Dun Laoghaire-full.webp"
  },
  {
    "title": "Caught Mid Snack",
    "subtitle": "Botanical Gardens",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/52 - Caught Mid Snack - Botanical Gardens-grid.webp",
    "full": "images/52 - Caught Mid Snack - Botanical Gardens-full.webp"
  },
  {
    "title": "Quiet Majesty",
    "subtitle": "Phoenix Park",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/53 - Quiet Majesty - Phoenix Park-grid.webp",
    "full": "images/53 - Quiet Majesty - Phoenix Park-full.webp"
  },
  {
    "title": "A Stately Ride",
    "subtitle": "Pheonx Park",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/54 - A Stately Ride - Pheonx Park-grid.webp",
    "full": "images/54 - A Stately Ride - Pheonx Park-full.webp"
  },
  {
    "title": "Next Stop, Spring",
    "subtitle": "Amsterdam",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/55 - Next Stop, Spring - Amsterdam-grid.webp",
    "full": "images/55 - Next Stop, Spring - Amsterdam-full.webp"
  },
  {
    "title": "Emerald Wings",
    "subtitle": "Malahide Castle",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/56 - Emerald Wings - Malahide Castle-grid.webp",
    "full": "images/56 - Emerald Wings - Malahide Castle-full.webp"
  },
  {
    "title": "Coastal Calm",
    "subtitle": "40 Foot",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/57 - Coastal Calm - 40 Foot-grid.webp",
    "full": "images/57 - Coastal Calm - 40 Foot-full.webp"
  },
  {
    "title": "Garden Elegance",
    "subtitle": "Airfield Estate",
    "width": 1023,
    "height": 1537,
    "shape": "portrait",
    "grid": "images/58 - Garden Elegance - Airfield Estate-grid.webp",
    "full": "images/58 - Garden Elegance - Airfield Estate-full.webp"
  },
  {
    "title": "Fly Me To The Moon",
    "subtitle": "Front Garden",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/59 - Fly Me To The Moon - Front Garden-grid.webp",
    "full": "images/59 - Fly Me To The Moon - Front Garden-full.webp"
  },
  {
    "title": "At The Water’s Edge",
    "subtitle": "Dublin Zoo",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/60 - At The Water's Edge - Dublin Zoo-grid.webp",
    "full": "images/60 - At The Water's Edge - Dublin Zoo-full.webp"
  },
  {
    "title": "A Gentle Greeting",
    "subtitle": "Dublin Zoo",
    "width": 6000,
    "height": 4000,
    "shape": "landscape",
    "grid": "images/61 - A Gentle Greeting - Dublin Zoo-grid.webp",
    "full": "images/61 - A Gentle Greeting - Dublin Zoo-full.webp"
  },
  {
    "title": "Standing Tall",
    "subtitle": "Dublin Zoo",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/62 - Standing Tall - Dublin Zoo-grid.webp",
    "full": "images/62 - Standing Tall - Dublin Zoo-full.webp"
  },
  {
    "title": "Dressed In Starlight",
    "subtitle": "Dun Laoghaire Pier",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/63 - Dressed In Starlight - Dun Laoghaire Pier-grid.webp",
    "full": "images/63 - Dressed In Starlight - Dun Laoghaire Pier-full.webp"
  },
  {
    "title": "Colour On The Water",
    "subtitle": "Botanical Gardens",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/64 - Colour On The Water - Botanical Gardens-grid.webp",
    "full": "images/64 - Colour On The Water - Botanical Gardens-full.webp"
  },
  {
    "title": "Eyes Of The Wild",
    "subtitle": "My Back Garden",
    "width": 1560,
    "height": 1040,
    "shape": "landscape",
    "grid": "images/65 - Eyes Of The Wild - My Back Garden-grid.webp",
    "full": "images/65 - Eyes Of The Wild - My Back Garden-full.webp"
  },
  {
    "title": "Glendalough In Green",
    "subtitle": "Gelndalough",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/66 - Glendalough In Green - Gelndalough-grid.webp",
    "full": "images/66 - Glendalough In Green - Gelndalough-full.webp"
  },
  {
    "title": "Into The Green",
    "subtitle": "Airfield Estate",
    "width": 1023,
    "height": 1537,
    "shape": "portrait",
    "grid": "images/67 - Into The Green - Airfield Estate-grid.webp",
    "full": "images/67 - Into The Green - Airfield Estate-full.webp"
  },
  {
    "title": "Flight Path",
    "subtitle": "Goats Town",
    "width": 6240,
    "height": 4160,
    "shape": "landscape",
    "grid": "images/68 - Flight Path - Goats Town-grid.webp",
    "full": "images/68 - Flight Path - Goats Town-full.webp"
  },
  {
    "title": "Beacon In The Mist",
    "subtitle": "Howth",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/69 - Beacon In The Mist - Howth-grid.webp",
    "full": "images/69 - Beacon In The Mist - Howth-full.webp"
  },
  {
    "title": "City In Reflection",
    "subtitle": "Paris",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/70 - City In Reflection - Paris-grid.webp",
    "full": "images/70 - City In Reflection - Paris-full.webp"
  },
  {
    "title": "The Whole Troop",
    "subtitle": "Dublin Zoo",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/71 - The Whole Troop - Dublin Zoo-grid.webp",
    "full": "images/71 - The Whole Troop - Dublin Zoo-full.webp"
  },
  {
    "title": "Regal Gaze",
    "subtitle": "Dublin Zoon",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/72 - Regal Gaze - Dublin Zoon-grid.webp",
    "full": "images/72 - Regal Gaze - Dublin Zoon-full.webp"
  },
  {
    "title": "Telegraph Cairn",
    "subtitle": "Dollymount Strand",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/73 - Telegraph Cairn - Dollymount Strand-grid.webp",
    "full": "images/73 - Telegraph Cairn - Dollymount Strand-full.webp"
  },
  {
    "title": "Lunch With A View",
    "subtitle": "Dublin Zoo",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/74 - Lunch With A View - Dublin Zoo-grid.webp",
    "full": "images/74 - Lunch With A View - Dublin Zoo-full.webp"
  },
  {
    "title": "By The Firelight",
    "subtitle": "St Fintans Park",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/75 - By The Firelight - St Fintans Park-grid.webp",
    "full": "images/75 - By The Firelight - St Fintans Park-full.webp"
  },
  {
    "title": "On The Wing At Poolbeg",
    "subtitle": "Dun Laoghaire",
    "width": 1023,
    "height": 1537,
    "shape": "portrait",
    "grid": "images/76 - On The Wing At Poolbeg - Dun Laoghaire-grid.webp",
    "full": "images/76 - On The Wing At Poolbeg - Dun Laoghaire-full.webp"
  },
  {
    "title": "Lighting Up The Night",
    "subtitle": "Dun Laoghaire Town Hall",
    "width": 1536,
    "height": 1024,
    "shape": "landscape",
    "grid": "images/77 - Lighting Up The Night - Dun Laoghaire Town Hall-grid.webp",
    "full": "images/77 - Lighting Up The Night - Dun Laoghaire Town Hall-full.webp"
  },
  {
    "title": "A Quiet Moment Of Reflection",
    "subtitle": "Dalkey",
    "width": 1402,
    "height": 1122,
    "shape": "landscape",
    "grid": "images/78 - A Quiet Moment Of Reflection - Dalkey-grid.webp",
    "full": "images/78 - A Quiet Moment Of Reflection - Dalkey-full.webp"
  },
  {
    "title": "Queen Of The Jungle",
    "subtitle": "Dublin Zoo",
    "width": 6000,
    "height": 4000,
    "shape": "landscape",
    "grid": "images/79 - Queen Of The Jungle - Dublin Zoo-grid.webp",
    "full": "images/79 - Queen Of The Jungle - Dublin Zoo-full.webp"
  },
  {
    "title": "Chasing the Light",
    "subtitle": "Killiney Hill",
    "width": 3000,
    "height": 2000,
    "shape": "landscape",
    "grid": "images/80 - Chasing the Light - Killiney Hill-grid.webp",
    "full": "images/80 - Chasing the Light - Killiney Hill-full.webp"
  },
  {
    "title": "Among The Moss And Muted Woodland",
    "subtitle": "Roundwood",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/81 - Among The Moss And Muted Woodland - Roundwood-grid.webp",
    "full": "images/81 - Among The Moss And Muted Woodland - Roundwood-full.webp"
  },
  {
    "title": "A Roar Awakens",
    "subtitle": "Dublin Zoo",
    "width": 1402,
    "height": 1122,
    "shape": "landscape",
    "grid": "images/82 - A Roar Awakens - Dublin Zoo-grid.webp",
    "full": "images/82 - A Roar Awakens - Dublin Zoo-full.webp"
  },
  {
    "title": "Mum In The Wind",
    "subtitle": "Greystones",
    "width": 1536,
    "height": 1024,
    "shape": "landscape",
    "grid": "images/83 - Mum In The Wind - Greystones-grid.webp",
    "full": "images/83 - Mum In The Wind - Greystones-full.webp"
  },
  {
    "title": "Between Sea & Sky",
    "subtitle": "Howth",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/84 - Between Sea and Sky - Howth-grid.webp",
    "full": "images/84 - Between Sea and Sky - Howth-full.webp"
  },
  {
    "title": "I See Ewe",
    "subtitle": "Roundwood",
    "width": 3864,
    "height": 2576,
    "shape": "landscape",
    "grid": "images/85 - I See Ewe - Roundwood-grid.webp",
    "full": "images/85 - I See Ewe - Roundwood-full.webp"
  },
  {
    "title": "Coming In For Landing",
    "subtitle": "Killiney Hill",
    "width": 2080,
    "height": 3120,
    "shape": "portrait",
    "grid": "images/86 - Coming In For Landing - Killiney Hill-grid.webp",
    "full": "images/86 - Coming In For Landing - Killiney Hill-full.webp"
  },
  {
    "title": "A Quiet Moment In A Place Full Of Stories",
    "subtitle": "Henrieta House",
    "width": 1537,
    "height": 1023,
    "shape": "landscape",
    "grid": "images/87 - A Quiet Moment In A Place Full Of Stories - Henrieta House-grid.webp",
    "full": "images/87 - A Quiet Moment In A Place Full Of Stories - Henrieta House-full.webp"
  },
  {
    "title": "Putting Away The Sun",
    "subtitle": "Dun Laoghaire",
    "width": 3120,
    "height": 2080,
    "shape": "landscape",
    "grid": "images/88 - Putting Away The Sun - Dun Laoghaire-grid.webp",
    "full": "images/88 - Putting Away The Sun - Dun Laoghaire-full.webp"
  },
  {
    "title": "She Chose Violins",
    "subtitle": "Dun Laoghaire",
    "width": 1536,
    "height": 1024,
    "shape": "landscape",
    "grid": "images/89 - She Chose Violins - Dun Laoghaire-grid.webp",
    "full": "images/89 - She Chose Violins - Dun Laoghaire-full.webp"
  },
  {
    "title": "Commanding The Quiet",
    "subtitle": "Dublin",
    "width": 1448,
    "height": 1086,
    "shape": "landscape",
    "grid": "images/90 - Commanding The Quiet - Dublin-grid.webp",
    "full": "images/90 - Commanding The Quiet - Dublin-full.webp"
  },
  {
    "title": "Joy In Every Note",
    "subtitle": "Florence",
    "width": 1023,
    "height": 1537,
    "shape": "portrait",
    "grid": "images/91 - Joy In Every Note - Florence-grid.webp",
    "full": "images/91 - Joy In Every Note - Florence-full.webp"
  },
  {
    "title": "A Rose Between Notes",
    "subtitle": "Florence",
    "width": 1023,
    "height": 1537,
    "shape": "portrait",
    "grid": "images/92 - A Rose Between Notes - Florence-grid.webp",
    "full": "images/92 - A Rose Between Notes - Florence-full.webp"
  },
  {
    "title": "Colour After The Rain",
    "subtitle": "Dublin",
    "width": 1024,
    "height": 1536,
    "shape": "portrait",
    "grid": "images/93 - Colour After The Rain - Dublin-grid.webp",
    "full": "images/93 - Colour After The Rain - Dublin-full.webp"
  },
  {
    "title": "A Silent Procession",
    "subtitle": "Bushy Park",
    "width": 2576,
    "height": 3864,
    "shape": "portrait",
    "grid": "images/94 - A Silent Procession - Bushy Park-grid.webp",
    "full": "images/94 - A Silent Procession - Bushy Park-full.webp"
  },
  {
    "title": "The City Below",
    "subtitle": "Dublin",
    "width": 1536,
    "height": 1024,
    "shape": "landscape",
    "grid": "images/95 - The City Below - Dublin-grid.webp",
    "full": "images/95 - The City Below - Dublin-full.webp"
  },
  {
    "title": "Golden Light Across Howth",
    "subtitle": "Howth",
    "width": 1672,
    "height": 941,
    "shape": "landscape",
    "grid": "images/96 - Golden Light Across Howth - Howth-grid.webp",
    "full": "images/96 - Golden Light Across Howth - Howth-full.webp"
  },
  {
    "title": "Reflections Of Quiet Nature",
    "subtitle": "Amsterdam",
    "width": 1024,
    "height": 1536,
    "shape": "portrait",
    "grid": "images/97 - Reflections Of Quiet Nature - Amsterdam-grid.webp",
    "full": "images/97 - Reflections Of Quiet Nature - Amsterdam-full.webp"
  },
  {
    "title": "Wings Of Tropical Wonder",
    "subtitle": "Amsterdam",
    "width": 1024,
    "height": 1536,
    "shape": "portrait",
    "grid": "images/98 - Wings Of Tropical Wonder - Amsterdam-grid.webp",
    "full": "images/98 - Wings Of Tropical Wonder - Amsterdam-full.webp"
  }
];
